import json

from src.domain.models import Config
from src.domain.publish import (
    build_manifest,
    get_command,
    manifest_entry,
    parse_get_output,
    source_signature,
    wrap_source_js,
)
from src.domain.result import Err, Ok

_PAYLOAD = {
    "meta": {
        "name": "CRM", "key": "customer_id", "as_of": 100.0, "generated_at": 200.0,
        "gen_max_cnt": 8, "include_archive": False, "rows": 2,
        "labels": ["email", "phone"],
    },
    "data": [
        {"customer_id": "1", "email": "a@x"},
        {"customer_id": "2", "phone": None},
    ],
}


def _named(name, **meta):
    p = json.loads(json.dumps(_PAYLOAD))
    p["meta"]["name"] = name
    p["meta"].update(meta)
    return p


# --- get_command ------------------------------------------------------------


def test_get_command_without_preset():
    cfg = Config(update_dir="u", db_path="d.db")
    assert get_command(cfg) == ["--db", "d.db", "get"]


def test_get_command_with_preset():
    cfg = Config(update_dir="u", db_path="d.db", webui_preset="p.json")
    assert get_command(cfg) == ["--db", "d.db", "get", "--preset", "p.json"]


# --- parse_get_output -----------------------------------------------------


def test_parse_single_bare_payload():
    r = parse_get_output(json.dumps(_PAYLOAD))
    assert isinstance(r, Ok) and set(r.value) == {"CRM"}
    assert r.value["CRM"]["meta"]["gen_max_cnt"] == 8


def test_parse_multi_source_map():
    doc = {"CRM": _PAYLOAD, "ERP": _named("ERP")}
    r = parse_get_output(json.dumps(doc))
    assert isinstance(r, Ok) and set(r.value) == {"CRM", "ERP"}


def test_parse_empty_object_is_ok_empty():
    r = parse_get_output("{}")
    assert isinstance(r, Ok) and r.value == {}


def test_parse_blank_is_err():
    assert isinstance(parse_get_output("   \n"), Err)


def test_parse_garbage_is_err():
    assert isinstance(parse_get_output("not json"), Err)


def test_parse_non_object_is_err():
    assert isinstance(parse_get_output("[1, 2]"), Err)


def test_parse_rejects_bad_source_shape():
    assert isinstance(parse_get_output('{"CRM": {"meta": {}}}'), Err)


# --- source_signature ---------------------------------------------------


def test_signature_tracks_gen_max_cnt():
    assert source_signature(_named("CRM", gen_max_cnt=9)) != source_signature(_PAYLOAD)


def test_signature_tracks_labels():
    assert source_signature(_named("CRM", labels=["email"])) != source_signature(_PAYLOAD)


def test_signature_stable_across_as_of_and_generated_at_drift():
    drifted = _named("CRM", as_of=999999.0, generated_at=8.0e9)
    assert source_signature(drifted) == source_signature(_PAYLOAD)


# --- wrap_source_js ----------------------------------------------------


def test_wrap_source_js_shape():
    js = wrap_source_js("CRM", _PAYLOAD)
    assert js.startswith("// GENERATED by ds-loader")
    assert "window.DS = window.DS || { sources: {} };" in js
    assert 'window.DS.sources["CRM"] = {' in js
    assert js.rstrip().endswith("};")
    body = json.loads(js.split("] = ", 1)[1].rstrip()[:-1])
    assert body["meta"]["name"] == "CRM"
    assert body["data"][1]["phone"] is None


# --- manifest_entry / build_manifest ---------------------------------


def test_manifest_entry_db_max_cnt_equals_gen_max_cnt():
    assert manifest_entry(_PAYLOAD) == {
        "name": "CRM", "file": "CRM.js", "key": "customer_id",
        "as_of": 100.0, "generated_at": 200.0,
        "gen_max_cnt": 8, "db_max_cnt": 8, "rows": 2,
        "labels": ["email", "phone"],
    }


def _manifest_doc(js):
    return json.loads(js.split("window.DS_MANIFEST = ", 1)[1].rstrip()[:-1])


def test_build_manifest_structure():
    js = build_manifest([manifest_entry(_PAYLOAD), manifest_entry(_named("ERP", gen_max_cnt=5))],
                        generated_at=999.0)
    assert js.startswith("// GENERATED by ds-loader")
    doc = _manifest_doc(js)
    assert doc["generated_at"] == 999.0
    assert doc["db_max_cnt"] == 8            # max по источникам
    assert [s["name"] for s in doc["sources"]] == ["CRM", "ERP"]


def test_build_manifest_empty():
    doc = _manifest_doc(build_manifest([], generated_at=1.0))
    assert doc["db_max_cnt"] == 0 and doc["sources"] == []
