from __future__ import annotations

import json
from typing import Dict, List

from src.domain.models import Config
from src.domain.result import Err, Ok

# Чистые функции стадии `publish`: построение argv для `ds get`, разбор его вывода,
# обёртка в `.js` и сборка `manifest.js` под файловый контракт `ds-webui`
# (ds-webui/docs/contract.md). Без I/O — эффекты в src/app/publish.py.

_JS_HEADER = "// GENERATED by ds-loader (стадия publish) из вывода `ds get` — не редактировать.\n"
_MANIFEST_HEADER = (
    "// GENERATED by ds-loader (стадия publish) рядом с <Source>.js — не редактировать.\n"
    "// Детект устаревания в ds-webui: db_max_cnt vs gen_max_cnt по каждому источнику.\n"
)


def get_command(cfg: Config) -> List[str]:
    """argv для `ds` БЕЗ префикса запуска (его добавляет адаптер DsCli).

    Итог: ds --db <db> get [--preset <preset>]  (вывод — в stdout, голый JSON).
    """
    args = ["--db", cfg.db_path, "get"]
    if cfg.webui_preset:
        args += ["--preset", cfg.webui_preset]
    return args


def _is_payload(obj: object) -> bool:
    return (
        isinstance(obj, dict)
        and isinstance(obj.get("meta"), dict)
        and "name" in obj["meta"]
        and isinstance(obj.get("data"), list)
    )


def parse_get_output(stdout: str) -> "Ok[Dict[str, dict]] | Err[str]":
    """Нормализовать вывод `ds get` в {имя источника: {meta, data}}.

    `ds get` печатает: один голый payload при единственном источнике,
    объект {имя: payload} при нескольких, `{}` при пустой БД.
    Пустой или неразобранный вывод → Err.
    """
    text = stdout.strip()
    if not text:
        return Err("ds get не вернул вывод")
    try:
        obj = json.loads(text)
    except ValueError as exc:
        return Err("не разобран вывод ds get: " + str(exc))
    if not isinstance(obj, dict):
        return Err("вывод ds get не JSON-объект")
    if not obj:
        return Ok({})
    if _is_payload(obj):
        return Ok({str(obj["meta"]["name"]): obj})
    out: Dict[str, dict] = {}
    for name, payload in obj.items():
        if not _is_payload(payload):
            return Err("неожиданная форма вывода ds get у источника " + str(name))
        out[str(name)] = payload
    return Ok(out)


def source_signature(payload: dict) -> str:
    """Отпечаток содержимого источника для гейтинга перезаписи.

    `as_of` / `generated_at` не включаем: при публикации на `as_of = now` они
    дрейфуют каждый тик, а свёртка детерминирована — данные не меняются, пока
    `gen_max_cnt` (максимальный cnt в срезе) тот же.
    """
    meta = payload["meta"]
    labels = ",".join(meta.get("labels", []))
    return "{0}|{1}|{2}".format(meta.get("gen_max_cnt", 0), meta.get("rows", 0), labels)


def wrap_source_js(name: str, payload: dict) -> str:
    """Текст `data/<name>.js`: присваивание в window.DS.sources[...]."""
    return (
        _JS_HEADER
        + "// Формат: ds-webui/docs/contract.md\n"
        + "window.DS = window.DS || { sources: {} };\n"
        + "window.DS.sources["
        + json.dumps(name, ensure_ascii=False)
        + "] = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + ";\n"
    )


def manifest_entry(payload: dict) -> dict:
    """Запись источника для `manifest.js` из `payload["meta"]`.

    v1: `db_max_cnt = gen_max_cnt`. `ds-loader` связан с ядром только через CLI, а
    `ds get` отдаёт лишь `gen_max_cnt` (максимум cnt в срезе `as_of`). При
    публикации на `as_of = now` это и есть текущий максимум источника в БД.
    Отдельный зонд «сырого max по БД» — см. docs/roadmap/README.md.
    """
    meta = payload["meta"]
    gen = meta.get("gen_max_cnt", 0)
    return {
        "name": meta["name"],
        "file": str(meta["name"]) + ".js",
        "key": meta.get("key"),
        "as_of": meta.get("as_of"),
        "generated_at": meta.get("generated_at"),
        "gen_max_cnt": gen,
        "db_max_cnt": gen,
        "rows": meta.get("rows", 0),
        "labels": meta.get("labels", []),
    }


def build_manifest(entries: List[dict], generated_at: float) -> str:
    """Текст `data/manifest.js`: window.DS_MANIFEST со списком источников."""
    doc = {
        "generated_at": generated_at,
        "db_max_cnt": max((e["gen_max_cnt"] for e in entries), default=0),
        "sources": entries,
    }
    return (
        _MANIFEST_HEADER
        + "window.DS_MANIFEST = "
        + json.dumps(doc, ensure_ascii=False, indent=2)
        + ";\n"
    )
